
yandex_prac_vm:
  children:
    prac:
      hosts: 
        vm1: 
          ansible_host: 93.77.185.69
        vm2: 
          ansible_host: 62.84.118.18
        vm3: 
          ansible_host: 62.84.127.132

  vars: 
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/selectel_key 
    connection_protocol: ssh 
    
    # ansible_become: true #Становиться ли другим пользователем после подключения
    # ansible_become_user: root #На какого пользователя переключиться после подключения
    # ansible_become_method: su #Метод перехода под другого пользователя
