
yandex_prac_vm:
  children:
    prac:
      hosts: 
        vm1: 
          ansible_host: 111.88.242.34
          internal_ip: 10.10.10.4
        vm2: 
          ansible_host: 111.88.241.236
          internal_ip: 10.10.10.10
        vm3: 
          ansible_host: 111.88.245.106
          internal_ip: 10.10.10.9

  vars: 
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/selectel_key 
    connection_protocol: ssh 
    ansible_become: true 
